matrix:
  include:
    - language: ruby
      rvm: 2.5.1
      sudo: false
      before_script:
        - cd armitage-rubocop
        - gem install bundler
        - bundle install --path vendor/bundle
      script:
        - bundle exec rake armitage_rubocop:build
