matrix:
  include:
    - language: ruby
      rvm: 2.5.1
      sudo: false
      cache: bundler
      before_script:
        - cd rubocop
        - gem install bundler
        - bundle install --path vendor/bundle
      script:
        - bundle exec rake rubocop
        - bundle exec rake armitage_rubocop:validation:valid_yamls
        - bundle exec rake armitage_rubocop:validation:recognizable_cops
