module.exports = {
  rules: {
    'array-bracket-newline': ['error', 'consistent'],
    'array-bracket-spacing': ['error', 'never'],
    'array-element-newline': ['off', { 'multiLine': true, 'minItems': 3 }],
    'block-spacing': ['error', 'always'],
    'brace-style': ['error', '1tbs', { 'allowSingleLine': true }],
    'camelcase': ['error', { 'properties': 'never', 'ignoreDestructuring': false }],
    'capitalized-comments': 'off',
    'comma-dangle': ['error', {
      'arrays': 'never',
      'functions': 'never',
      'objects': 'never',
      'imports': 'never',
      'exports': 'never'
    }],
    'comma-spacing': ['error', { 'before': false, 'after': true }],
    'comma-style': ['error', 'last', {
      'exceptions': {
        'ArrayExpression': false,
        'ArrayPattern': false,
        'ArrowFunctionExpression': false,
        'CallExpression': false,
        'FunctionDeclaration': false,
        'FunctionExpression': false,
        'ImportDeclaration': false,
        'ObjectExpression': false,
        'ObjectPattern': false,
        'VariableDeclaration': false,
        'NewExpression': false
      }
    }],
    'computed-property-spacing': ['error', 'never'],
    'consistent-this': 'off',
    'eol-last': ['error', 'always'],
    'func-call-spacing': ['error', 'never'],
    'func-name-matching': ['off', { 'considerPropertyDescriptor': true, 'includeCommonJSModuleExports': false }],
    'func-names': 'off',
    'func-style': 'off',
    'function-paren-newline': ['error', 'multiline'],
    'id-blacklist': 'off',
    'id-length': 'off',
    'id-match': 'off',
    'implicit-arrow-linebreak': ['error', 'beside'],
    'indent': ['error', 2, {
      'SwitchCase': 1,
      'VariableDeclarator': 1,
      'outerIIFEBody': 1,
      'FunctionDeclaration': { 'parameters': 1, 'body': 1 },
      'FunctionExpression': { 'parameters': 2, 'body': 1 },
      'CallExpression': { 'arguments': 1 },
      'ArrayExpression': 1,
      'ObjectExpression': 1,
      'ImportDeclaration': 1,
      'flatTernaryExpressions': true,
      'ignoreComments': false,
      'ignoredNodes': [ // https://github.com/benjamn/ast-types/blob/master/def/jsx.js
        'JSXAttribute',
        'JSXIdentifier',
        'JSXNamespacedName',
        'JSXMemberExpression',
        'JSXNamespacedName',
        'JSXMemberExpression',
        'JSXSpreadAttribute',
        'JSXExpressionContainer',
        'JSXElement',
        'JSXElement > *',
        'JSXOpeningElement',
        'JSXClosingElement',
        'JSXFragment',
        'JSXFragment > *',
        'JSXOpeningFragment',
        'JSXClosingFragment',
        'JSXText',
        'JSXEmptyExpression',
        'JSXSpreadChild'
      ]
    }],
    'jsx-quotes': ['error', 'prefer-double'],
    'key-spacing': ['error', {
      'beforeColon': false,
      'afterColon': true,
      'mode': 'strict',
      'align': 'value'
    }],
    'keyword-spacing': [ 'error', {
      'before': true,
      'after': true,
      'overrides': {
        'return': { 'after': true },
        'throw': { 'after': true },
        'case': { 'after': true }
      }
    }],
    'line-comment-position': 'off',
    'linebreak-style': ['error', 'unix'],
    'lines-around-comment': 'off',
    'lines-between-class-members': ['error', 'always', { 'exceptAfterSingleLine': true }],
    'max-depth': 'off',
    'max-len': ['error', { 'code': 100, 'tabWidth': 2 }],
    'max-lines': ['off', { 'max': 300, 'skipBlankLines': true, 'skipComments': true }],
    'max-lines-per-function': ['off', { 'max': 25, 'skipBlankLines': true, 'skipComments': true, 'IIFEs': false }],
    'max-nested-callbacks': ['off', { 'max': 10 }],
    'max-params': ['off', { 'max': 3 }],
    'max-statements': ['off', { 'max': 10 }],
    'max-statements-per-line': ['off', { 'max': 1 }],
    'multiline-comment-style': 'off',
    'multiline-ternary': ['off', 'never'],
    'new-cap': ['error', {
      'newIsCap': true,
      'newIsCapExceptions': [],
      'capIsNew': false,
      'capIsNewExceptions': [],
      'properties': true
    }],
    'new-parens': ['error', 'always'],
    'newline-per-chained-call': ['error', { 'ignoreChainWithDepth': 4 }],
    'no-array-constructor': 'error',
    'no-bitwise': 'off',
    'no-continue': 'off',
    'no-inline-comments': 'off',
    'no-lonely-if': 'error',
    'no-mixed-operators': ['error', {
      'groups': [
        ['%', '**'],
        ['%', '+'],
        ['%', '-'],
        ['%', '*'],
        ['%', '/'],
        ['/', '*'],
        ['&', '|', '<<', '>>', '>>>'],
        ['==', '!=', '===', '!=='],
        ['&&', '||']
      ],
      'allowSamePrecedence': false
    }],
    'no-mixed-spaces-and-tabs': 'error',
    'no-multi-assign': 'error',
    'no-multiple-empty-lines': ['error', { 'max': 1, 'maxEOF': 1, 'maxBOF': 0 }],
    'no-negated-condition': 'off',
    'no-nested-ternary': 'error',
    'no-new-object': 'off',
    'no-plusplus': ['error', { 'allowForLoopAfterthoughts': true }],
    'no-restricted-syntax': 'off',
    'no-tabs': 'error',
    'no-ternary': 'off',
    'no-trailing-spaces': ['error', { 'skipBlankLines': false, 'ignoreComments': false }],
    'no-underscore-dangle': 'off',
    'no-unneeded-ternary': ['error', { 'defaultAssignment': true }],
    'no-whitespace-before-property': 'error',
    'nonblock-statement-body-position': ['error', 'beside'],
    'object-curly-newline': ['error', {
      'ObjectExpression': { 'multiline': true, 'minProperties': 4, 'consistent': true },
      'ObjectPattern': { 'multiline': true, 'minProperties': 4, 'consistent': true },
      'ImportDeclaration': { 'multiline': true, 'minProperties': 4, 'consistent': true },
      'ExportDeclaration': { 'multiline': true, 'minProperties': 4, 'consistent': true }
    }],
    'object-curly-spacing': ['error', 'always'],
    'object-property-newline': ['error', { 'allowAllPropertiesOnSameLine': true }],
    'one-var': ['error', 'never'],
    'one-var-declaration-per-line': 'off',
    'operator-assignment':  ['error', 'always'],
    'operator-linebreak': ['error', 'after'],
    'padded-blocks': ['error', {
      'blocks': 'never',
      'classes': 'never',
      'switches': 'never'
    }, { 'allowSingleLineBlocks': true }],
    'padding-line-between-statements': 'off',
    'prefer-object-spread': 'error',
    'quote-props': ['error', 'as-needed', {
      'keywords': false,
      'unnecessary': true,
      'numbers': false
    }],
    'quotes': ['error', 'single', { 'avoidEscape': true }],
    'semi': ['error', 'never'],
    'semi-spacing': ['error', { 'before': false, 'after': true }],
    'semi-style': ['error', 'last'],
    'sort-keys': 'off',
    'sort-vars': 'off',
    'space-before-blocks': ['error', 'always'],
    'space-before-function-paren': ['error', {
      'anonymous': 'always',
      'named': 'never',
      'asyncArrow': 'always'
    }],
    'space-in-parens': ['error', 'never'],
    'space-infix-ops': 'error',
    'space-unary-ops': ['error', { 'words': true, 'nonwords': false }],
    'spaced-comment': ['error', 'always'],
    'switch-colon-spacing': ['error', { 'after': true, 'before': false }],
    'template-tag-spacing': ['error', 'never'],
    'unicode-bom': ['error', 'never'],
    'wrap-regex': 'off'
  }
}
