inherit_from:
  - ./lib/rubocop.general.yml
  - ./lib/rubocop.rake.yml
  - ./lib/rubocop.rspec.yml
  - ./lib/rubocop.rails.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  StringLiteralsFrozenByDefault: true
